/*
 * DimensionPanel.java
 *
 * Created on 20 / novembre / 2002, 08:49
 */

package edu.xtec.qv.editor.ui;

/**
 *
 * @author  allastar
 */
public class DimensionPanel extends javax.swing.JPanel {
            
    /** Creates new form DimensionPanel */
    public DimensionPanel() {
        initComponents();    
    }
    
    public void setMediaWidth(String s){
        jTextField1.setText(s);
    }
    
    public void setMediaHeight(String s){
        jTextField2.setText(s);
    }
    
    public int getMediaWidth(){
        int iWidth=-1;
        String sWidth=jTextField1.getText();
        try{
            iWidth=(int)Double.parseDouble(sWidth);
        }
        catch (Exception e){
            jTextField1.setText("");
        }
        return iWidth;
    }
        
    public int getMediaHeight(){
        int iHeight=-1;
        String sHeight=jTextField2.getText();
        try{
            iHeight=(int)Double.parseDouble(sHeight);
        }
        catch (Exception e){
            jTextField2.setText("");
        }
        return iHeight;
    }	
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lbWidth = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbHeight = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        lbWidth.setText("Amplada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 3);
        add(lbWidth, gridBagConstraints);

        jTextField1.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 3);
        add(jTextField1, gridBagConstraints);

        lbHeight.setText("Al\u00e7ada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 3);
        add(lbHeight, gridBagConstraints);

        jTextField2.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 3);
        add(jTextField2, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHeight;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbWidth;
    // End of variables declaration//GEN-END:variables
    
}
