package edu.xtec.qv.editor.ui;

import edu.xtec.qv.editor.util.Icons;

/*
 * LoginDialog.java
 *
 * Created on 18 / desembre / 2002, 09:00
 */

/**
 *
 * @author  allastar
 */
public class LoginDialog extends javax.swing.JDialog {
    
    /** Creates new form LoginDialog */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initComponents2();
        setTitle("Entrada al sistema");
        //pack();
        setSize(420,200);
    }
    
    public String getId(){
        return tfUserName.getText();
    }
    
    public String getPwd(){
        return new String(tfPassword.getPassword());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jpCenter = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        tfUserName = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btOk = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jpCenter.setLayout(new java.awt.GridBagLayout());

        jpCenter.setBackground(new java.awt.Color(255, 255, 204));
        lbUserName.setText("Nom d'usuari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jpCenter.add(lbUserName, gridBagConstraints);

        tfUserName.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jpCenter.add(tfUserName, gridBagConstraints);

        lbPassword.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jpCenter.add(lbPassword, gridBagConstraints);

        tfPassword.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jpCenter.add(tfPassword, gridBagConstraints);

        btOk.setText("Entrar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(12, 4, 5, 4);
        jpCenter.add(btOk, gridBagConstraints);

        jPanel1.add(jpCenter, java.awt.BorderLayout.CENTER);

        lbLogo.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(lbLogo, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btOkActionPerformed
            
    protected void initComponents2(){
        lbLogo.setIcon(Icons.getIcon("LogoLogin"));
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new LoginDialog(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPanel jpCenter;
    private javax.swing.JTextField tfUserName;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton btOk;
    // End of variables declaration//GEN-END:variables
    
}
