/*
 * AssessmentManagePresentationPanel.java
 *
 * Created on 9 / desembre / 2002, 13:21
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.editor.util.Icons;
import edu.xtec.util.Messages;

/**
 *
 * @author  allastar
 */
public class ManagePresentationPanel extends javax.swing.JPanel {
    
    /** Creates new form AssessmentManagePresentationPanel */
    public ManagePresentationPanel() {
        initComponents();
        initComponents2();
        //initMessages();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        lbAssessmentManage = new javax.swing.JLabel();
        tpExplain = new javax.swing.JTextPane();
        jpLogo = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout(0, 30));

        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(300, 400));
        setMaximumSize(new java.awt.Dimension(600, 600));
        lbAssessmentManage.setFont(new java.awt.Font("Dialog", 1, 36));
        add(lbAssessmentManage, java.awt.BorderLayout.NORTH);

        tpExplain.setEditable(false);
        tpExplain.setFont(new java.awt.Font("Verdana", 0, 18));
        tpExplain.setBackground(new java.awt.Color(204, 204, 204));
        add(tpExplain, java.awt.BorderLayout.CENTER);

        add(jpLogo, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents
    
    protected void initComponents2(){
        try{
            javax.swing.JLabel lbLogo=new javax.swing.JLabel(Icons.getIcon("logo"));
            if (lbLogo!=null) jpLogo.add(lbLogo);
        }
        catch (Exception e){
        }
    }
    
    protected void initMessages(String sTitleKey, String sDescriptionKey){
	if (sTitleKey!=null) lbAssessmentManage.setText(Messages.getLocalizedString(sTitleKey));
	if (sDescriptionKey!=null) tpExplain.setText(Messages.getLocalizedString(sDescriptionKey));
        if (sTitleKey!=null) setToolTipText(Messages.getLocalizedString(sTitleKey));
    }
    
    protected void setTextColor(java.awt.Color c){
        lbAssessmentManage.setForeground(c);
        tpExplain.setForeground(c);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAssessmentManage;
    private javax.swing.JTextPane tpExplain;
    private javax.swing.JPanel jpLogo;
    // End of variables declaration//GEN-END:variables
    
}
