/*
 * QTIAssessmentPanel.java
 *
 * Created on 14 / octubre / 2002, 09:57
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIAssessment;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;
/**
 *
 * @author  allastar
 */
public class QTIAssessmentPanel extends javax.swing.JPanel implements ExtendedRenderer{
    
    protected QTIAssessment qtiAssessment;
    protected MetadataPropertiesPanel jpMetadataProperties;
    
    /** Creates new form QTIAssessmentPanel */
    public QTIAssessmentPanel(QTIAssessment qtiAssessment, String sIdent, String sTitle) {
        this.qtiAssessment=qtiAssessment;
        initComponents();
        initComponents2();
        if (jpMetadataProperties!=null) jpMetadataProperties.setID(sIdent);
        if (jpMetadataProperties!=null) jpMetadataProperties.setTitle(sTitle);
        //tfIdent.setText(sIdent);
        //tfTitle.setText(sTitle);
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    public void setMetadataPropertiesPanel(MetadataPropertiesPanel jpMetadataProperties){
        this.jpMetadataProperties=jpMetadataProperties;
        jTabbedPane1.addTab("Propietats", null, jpMetadataProperties, "");
    }
    
    ////public void setPresentationPanel(QTIMaterialPanel jpQTIMatPanel){
    public void setPresentationPanel(javax.swing.JPanel jpQTIMatPanel){
        jTabbedPane1.addTab(Messages.getLocalizedString("Presentation"), null, jpQTIMatPanel, "");
    }
    
    public void setInformationPanel(QTIInformationPanel jpInfoPanel){
        jTabbedPane1.addTab(Messages.getLocalizedString("Information"), null, jpInfoPanel, "");
    }
    
    public void setResponsesPanel(QTIContainerResponsesProcessingPanel jpResp){
        jTabbedPane1.addTab(Messages.getLocalizedString("Evaluation"), null, jpResp, Messages.getLocalizedString("NotebookEvaluation"));
    }
    
    public String getIdent(){
        return (jpMetadataProperties!=null)?jpMetadataProperties.getID():"";
    }
    
    public String getTitle(){
        return (jpMetadataProperties!=null)?jpMetadataProperties.getTitle():"";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void initComponents2(){
        
    }
    
    protected void initMessages(){
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        if (jpMetadataProperties!=null) jpMetadataProperties.setBackground(c);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
}