/*
 * QTIEqualConditionPanel.java
 *
 * Created on 7 / octubre / 2002, 08:58
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.jclic.shapers.utils.ShapeInfo;
import edu.xtec.qv.qti.QTIEqualCondition;
import edu.xtec.qv.qti.QTISelectionResponse;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;

/**
 *
 * @author  allastar
 */
public class QTIEqualConditionPanel extends javax.swing.JPanel implements ExtendedRenderer{
    
    protected QTIEqualCondition qtiEqCond;
    
    /** Creates new form QTIEqualConditionPanel */
    public QTIEqualConditionPanel(QTIEqualCondition qtiEqCond) {
        this.qtiEqCond=qtiEqCond;
        initComponents();
        initComponents2();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    public void setCase(boolean bCase){
        cbCase.setSelected(bCase);
    }
    
    public void setEqualTo(Object oEqualTo){
        //cbEqualTo.getModel().setSelectedItem(oEqualTo); //No sé que passa si no el té. Suposo que l'afegeix.
        //System.out.println("Panel-->setEqualTo:"+oEqualTo);
        boolean bFound=false;
        for (int i=0;i<cbEqualTo.getItemCount() && !bFound;i++){
            String sItemName=cbEqualTo.getItemAt(i).toString();
            if (sItemName.equals(oEqualTo.toString())){
                bFound=true;
                cbEqualTo.setSelectedIndex(i);
            }
        }
        if (!bFound){
            cbEqualTo.addItem(oEqualTo);
            cbEqualTo.setSelectedItem(oEqualTo);
        }
    }
    
    public void setPosibleValues(java.util.Vector vPosibleValues){
        //System.out.println("setPosibleValues");
        if (vPosibleValues!=null && vPosibleValues.size()>0){
            Object oSelected=cbEqualTo.getSelectedItem();
            cbEqualTo.removeAllItems();
            java.util.Enumeration e=vPosibleValues.elements();
            while (e.hasMoreElements()){
                Object id=e.nextElement();
                if (id instanceof QTISelectionResponse) cbEqualTo.addItem(((QTISelectionResponse)id).getIdent());
                else if (id instanceof ShapeInfo) cbEqualTo.addItem(((ShapeInfo)id).getIdent());
                else System.out.println("Cast!!!!!!!!!!!!! :"+e.getClass().getName()+"<--");
            }
            if (oSelected!=null){
                cbEqualTo.removeItem(oSelected);
                cbEqualTo.addItem(oSelected);
                cbEqualTo.setSelectedItem(oSelected);
            }
        }
    }
    
    public boolean getCase(){
        return cbCase.isSelected();
    }
    
    public Object getEqualTo(){
        //System.out.println("="+tfEqualTo.getText().toString());
        return cbEqualTo.getSelectedItem();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        cbCase = new javax.swing.JCheckBox();
        lbEqualTo = new javax.swing.JLabel();
        cbEqualTo = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        cbCase.setText("Sensible a maj\u00fascules");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(cbCase, gridBagConstraints);

        lbEqualTo.setText("igual a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 3);
        add(lbEqualTo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        add(cbEqualTo, gridBagConstraints);

    }//GEN-END:initComponents
    
    private void initComponents2(){
        cbEqualTo.setEditable(true);
    }
    
    protected void initMessages(){
        cbCase.setText(Messages.getLocalizedString("CaseSensitive"));
        lbEqualTo.setText(Messages.getLocalizedString("equalTo"));
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        java.awt.Color componentColor=CreatorProperties.getComponentColor();
        if (componentColor!=null){
            if (cbCase!=null) cbCase.setBackground(componentColor);
            if (cbEqualTo!=null) cbEqualTo.setBackground(componentColor);
            if (lbEqualTo!=null) lbEqualTo.setBackground(componentColor);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbCase;
    private javax.swing.JComboBox cbEqualTo;
    private javax.swing.JLabel lbEqualTo;
    // End of variables declaration//GEN-END:variables
    
}