/*
 * QTIFileChooserDialog.java
 *
 * Created on 22 / maig / 2003, 08:55
 */

package edu.xtec.qv.editor.ui;

/**
 *
 * @author  allastar
 */

import java.io.File;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

import edu.xtec.util.Messages;

public class QTIFileChooserDialog extends javax.swing.JDialog {
    
    /** Creates new form QTIFileChooserDialog */
    public QTIFileChooserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initComponents2();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jfc = new javax.swing.JFileChooser();
        lbInformation = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        getContentPane().add(jfc, java.awt.BorderLayout.CENTER);

        lbInformation.setText(" ");
        getContentPane().add(lbInformation, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents
    
    protected void initComponents2(){
        FileFilter ff=new FileFilter(){
            public boolean accept(File f){
                if (f.isDirectory()) return true;
                String sName=f.getName();
                if (sName!=null && sName.trim().length()>0){
                    sName=sName.trim();
                    int i=sName.lastIndexOf('.');
                    if (sName.length()>i){
                        String ext=sName.substring(i+1,sName.length());
                        if (ext.equals("xml") || ext.equals("qti")) return true;
                    }
                }
                return false;
            }
            
            public String getDescription(){
                return Messages.getLocalizedString("QTIFiles");
            }
        };
        jfc.setFileFilter(ff);
        
        lbInformation.setText("Ubicació del quadern");
    }
    
    public java.io.File showOpenDialog(java.awt.Component c){
        int returnVal=jfc.showOpenDialog(c);
        return jfc.getSelectedFile();
    }
    
    public java.io.File showSaveDialog(java.awt.Component c){
        lbInformation.setText("Selecciona la ubicació i decideix el nom del quadern que vols crear.");
        int returnVal=jfc.showSaveDialog(c);
        if (returnVal==JFileChooser.APPROVE_OPTION){
            File f=jfc.getSelectedFile();
            if (f.exists()){
                int option=JOptionPane.showConfirmDialog(jfc,"Aquest fitxer existeix. Segur que el vols sobreescriure?","Atenció!!!",JOptionPane.WARNING_MESSAGE,JOptionPane.YES_NO_OPTION);
                if (option!=JOptionPane.YES_OPTION){
                    return showSaveDialog(c);
                    //returnVal=showSaveDialog(c);
                }
                else return f;
            }
            else{
                try{
                    f.createNewFile();
                    return f;
                }
                catch (IOException e){
                    JOptionPane.showMessageDialog(jfc,"No s'ha pogut crear el quadern.","Error",JOptionPane.ERROR_MESSAGE);
                    return null;
                    //returnVal=JFileChooser.CANCEL_OPTION;
                }
            }
        }
        return null;
        //return returnVal;
    }

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        new QTIFileChooserDialog(new javax.swing.JFrame(), true).show();
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbInformation;
    private javax.swing.JFileChooser jfc;
    // End of variables declaration//GEN-END:variables
    
}
