/*
 * QTIItemResponsesPanel.java
 *
 * Created on 6 de octubre de 2002, 17:14
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIItemResponses;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;

/**
 *
 * @author  Albert
 * @version
 */
public class QTIItemResponsesPanel extends javax.swing.JPanel implements ExtendedRenderer{
    
    protected QTIItemResponses qtiItemResp;
    
    /** Creates new form QTIItemResponsesPanel */
    public QTIItemResponsesPanel(QTIItemResponses qtiItemResp, String sIdent) {
        this.qtiItemResp=qtiItemResp;
        initComponents();
        initComponents2();
        tfIdent.setText(sIdent);
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
    }
    
    public void setConcretePanel(javax.swing.JPanel jpQTIConcreteResponsesPanel, int iType){
        if (jpQTIConcreteResponsesPanel.getBorder() instanceof javax.swing.border.TitledBorder) spConcreteResponsePanel.setBorder(null);
        else spConcreteResponsePanel.setBorder(new javax.swing.border.EtchedBorder());
        spConcreteResponsePanel.setViewportView(jpQTIConcreteResponsesPanel);
        if (iType>=0){
            cbType.setSelectedIndex(iType);
        }
    }
    
    public void setIdent(String sIdent){
        tfIdent.setText(sIdent);
    }
    
    public String getIdent(){
        return tfIdent.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jpType = new javax.swing.JPanel();
        lbType = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox();
        lbIdent = new javax.swing.JLabel();
        tfIdent = new javax.swing.JTextField();
        spConcreteResponsePanel = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jpType.setLayout(new java.awt.GridBagLayout());

        lbType.setText("Tipus");
        lbType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jpType.add(lbType, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 10);
        jpType.add(cbType, gridBagConstraints);

        lbIdent.setText("Identificador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 5);
        jpType.add(lbIdent, gridBagConstraints);

        tfIdent.setColumns(15);
        tfIdent.setMinimumSize(new java.awt.Dimension(104, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jpType.add(tfIdent, gridBagConstraints);

        add(jpType, java.awt.BorderLayout.NORTH);

        spConcreteResponsePanel.setBorder(null);
        add(spConcreteResponsePanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void initComponents2(){
        spConcreteResponsePanel.setBorder(null);
        
        cbType.addItem("selecció");
        cbType.addItem("omplir espais");
        cbType.addItem("selecció dintre imatge");
        cbType.addItem("barra de selecció");
        cbType.addItem("ordenar");
        cbType.addItem("arrossegar");
        cbType.addItemListener(new java.awt.event.ItemListener(){
            public void itemStateChanged(java.awt.event.ItemEvent e){
                qtiItemResp.setResponsesType(cbType.getSelectedIndex());
            }
        });
        
        lbType.setToolTipText(Messages.getLocalizedString("ResponseTypeDesc"));
        cbType.setToolTipText(Messages.getLocalizedString("ResponseTypeDesc"));
        
        lbIdent.setToolTipText(Messages.getLocalizedString("ResponseIdentDesc"));
        tfIdent.setToolTipText(Messages.getLocalizedString("ResponseIdentDesc"));
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        if (jpType!=null) jpType.setBackground(c);
        if (spConcreteResponsePanel!=null) spConcreteResponsePanel.setBackground(c);
        java.awt.Color componentColor=CreatorProperties.getComponentColor();
        if (componentColor!=null){
            if (lbType!=null) lbType.setBackground(componentColor);
            if (cbType!=null) cbType.setBackground(componentColor);
            if (lbIdent!=null) lbIdent.setBackground(componentColor);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField tfIdent;
    private javax.swing.JLabel lbType;
    private javax.swing.JPanel jpType;
    private javax.swing.JComboBox cbType;
    private javax.swing.JLabel lbIdent;
    private javax.swing.JScrollPane spConcreteResponsePanel;
    // End of variables declaration//GEN-END:variables
    
}