/*
 * QTIInsideConditionPanel.java
 *
 * Created on 7 de octubre de 2002, 20:35
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIInsideCondition;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.qv.qti.util.ObjectListElement;
import edu.xtec.util.Messages;

/**
 *
 * @author  Albert
 * @version
 */
public class QTIInsideConditionPanel extends javax.swing.JPanel implements ExtendedRenderer{
    
    protected QTIInsideCondition qtiInsideCond;
    
    /** Creates new form QTIInsideConditionPanel */
    public QTIInsideConditionPanel(QTIInsideCondition qtiInsideCond) {
        this.qtiInsideCond=qtiInsideCond;
        initComponents();
        initComponents2();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    public int getAreaType(){
        return ((ObjectListElement)cbAreaType.getSelectedItem()).getId();
        //return -1;
    }
    
    public String getArea(){
        return tfArea.getText();
    }
    
    public void setAreaType(int iAreaType){
        cbAreaType.setSelectedIndex(iAreaType);
    }
    
    public void setArea(String sArea){
        tfArea.setText(sArea);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        lbAreaType = new javax.swing.JLabel();
        cbAreaType = new javax.swing.JComboBox();
        lbArea = new javax.swing.JLabel();
        tfArea = new javax.swing.JTextField();
        setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        lbAreaType.setText("tipus d'\u00e0rea");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(2, 8, 2, 2);
        add(lbAreaType, gridBagConstraints1);
        
        
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(2, 2, 2, 15);
        add(cbAreaType, gridBagConstraints1);
        
        
        lbArea.setText("\u00e0rea");
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(2, 15, 2, 2);
        add(lbArea, gridBagConstraints1);
        
        
        tfArea.setColumns(14);
        tfArea.setMinimumSize(new java.awt.Dimension(104, 20));
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(2, 2, 2, 8);
        add(tfArea, gridBagConstraints1);
        
    }//GEN-END:initComponents

    private void initComponents2(){
        cbAreaType.addItem(new ObjectListElement(QTIInsideCondition.RECTANGLE,"rectangle"));
        cbAreaType.addItem(new ObjectListElement(QTIInsideCondition.ELLIPSE,"el·lipse"));
        cbAreaType.addItem(new ObjectListElement(QTIInsideCondition.BOUNDED,"polígon"));
    }
    
    protected void initMessages(){
        lbAreaType.setText(Messages.getLocalizedString("areaType"));
        lbArea.setText(Messages.getLocalizedString("area"));
    }
    
    public void setBackground(java.awt.Color bgColor){
        super.setBackground(bgColor);
        java.awt.Color componentColor=CreatorProperties.getComponentColor();
        if (componentColor!=null){
            if (lbAreaType!=null) lbAreaType.setBackground(componentColor);
            if (cbAreaType!=null) cbAreaType.setBackground(componentColor);
            if (lbArea!=null) lbArea.setBackground(componentColor);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAreaType;
    private javax.swing.JComboBox cbAreaType;
    private javax.swing.JLabel lbArea;
    private javax.swing.JTextField tfArea;
    // End of variables declaration//GEN-END:variables
    
}