/*
 * QTILinkMaterialPanel.java
 *
 * Created on 21 / novembre / 2002, 10:13
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;

/**
 *
 * @author  allastar
 */
public class QTILinkMaterialPanel extends javax.swing.JPanel {
    
    /** Creates new form QTILinkMaterialPanel */
    public QTILinkMaterialPanel(String sURI) {
        initComponents();
        initComponents2(sURI);
        initMessages();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
    }
    
    public void setURI(String sURI){
        tfURI.setText(sURI);
    }
    
    public void setText(String sText){
        tfText.setText(sText);
    }
    
    public String getURI(){
        return tfURI.getText().trim();
    }
    
    public String getText(){
        return tfText.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lbURI = new javax.swing.JLabel();
        tfURI = new javax.swing.JTextField();
        lbText = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        lbURI.setText("URI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(lbURI, gridBagConstraints);

        tfURI.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 4);
        add(tfURI, gridBagConstraints);

        lbText.setText("Text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 4);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(lbText, gridBagConstraints);

        tfText.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 4, 7, 4);
        add(tfText, gridBagConstraints);

    }//GEN-END:initComponents
    
    protected void initComponents2(String sURI){
        tfURI.setText(sURI);
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        if (lbURI!=null) lbURI.setBackground(c);
        if (lbText!=null) lbText.setBackground(c);
    }
    
    protected void initMessages(){
        lbURI.setText(Messages.getLocalizedString("URL"));
        lbText.setText(Messages.getLocalizedString("Text"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbURI;
    private javax.swing.JTextField tfURI;
    private javax.swing.JLabel lbText;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
    
}
