/*
 * QTIMaterialPanel.java
 *
 * Created on 6 de octubre de 2002, 19:52
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIMaterial;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.qv.qti.util.ObjectListElement;
import edu.xtec.util.Messages;

/**
 *
 * @author  Albert
 * @version
 */
public class QTIMaterialPanel extends javax.swing.JPanel implements ExtendedRenderer{
    
    QTIMaterial qtiMat;
    protected String sTitle;
    protected static ObjectListElement[] materials=null;
    
    /** Creates new form QTIMaterialPanel */
    public QTIMaterialPanel(String sTitle, QTIMaterial qtiMat) {
        this(sTitle,qtiMat,null);
    }
    
    public QTIMaterialPanel(String sTitle, QTIMaterial qtiMat, int[] iAPossibleMaterial) {
        this.sTitle=sTitle;
        this.qtiMat=qtiMat;
        if (materials==null) initMaterials();
        initComponents();
        initComponents2(iAPossibleMaterial);
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    
    protected static void initMaterials(){
        materials=new ObjectListElement[9];
        materials[0]=new ObjectListElement(QTIMaterial.TEXT,Messages.getLocalizedString("Text"));
        materials[1]=new ObjectListElement(QTIMaterial.IMAGE,Messages.getLocalizedString("Image"));
        materials[2]=new ObjectListElement(QTIMaterial.AUDIO,Messages.getLocalizedString("Audio"));
        materials[3]=new ObjectListElement(QTIMaterial.VIDEO,Messages.getLocalizedString("Video"));
        materials[4]=new ObjectListElement(QTIMaterial.APPLET,Messages.getLocalizedString("Applet"));
        materials[5]=new ObjectListElement(QTIMaterial.CLIC,Messages.getLocalizedString("Clic"));
        materials[6]=new ObjectListElement(QTIMaterial.FLASH,Messages.getLocalizedString("Flash"));
        materials[7]=new ObjectListElement(QTIMaterial.LINK,Messages.getLocalizedString("Link"));
        materials[8]=new ObjectListElement(QTIMaterial.HTML,Messages.getLocalizedString("Html"));
    }
    
    public void setConcreteMaterialPanel(javax.swing.JPanel jpConcreteMaterialPanel){
        //spConcreteMaterialPanel.removeAll();
        spConcreteMaterialPanel.setViewportView(jpConcreteMaterialPanel);
        repaint();
    }
    
    public void setConcreteMaterialType(int iMaterialType){
        cbType.setSelectedIndex(iMaterialType);
    }
    
    public int getAlign(){
        return cbAlign.getSelectedIndex();
    }
    
    public void setAlign(int iAlign){
        cbAlign.setSelectedIndex(iAlign);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        lbType = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox();
        lbAlign = new javax.swing.JLabel();
        cbAlign = new javax.swing.JComboBox();
        spConcreteMaterialPanel = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        lbType.setText("Tipus");
        jPanel1.add(lbType);

        jPanel1.add(cbType);

        lbAlign.setText("Aliniaci\u00f3");
        jPanel1.add(lbAlign);

        jPanel1.add(cbAlign);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        spConcreteMaterialPanel.setBorder(null);
        spConcreteMaterialPanel.setAutoscrolls(true);
        add(spConcreteMaterialPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void initComponents2(int[] iAPossibleMaterial){
        if (sTitle==null || sTitle.trim().length()==0) sTitle="material";
        else setBorder(new javax.swing.border.TitledBorder(sTitle));
        for (int i=0;i<materials.length;i++){
            if (iAPossibleMaterial==null) cbType.addItem(materials[i]);
            else{
                boolean bFound=false;
                for (int j=0;j<iAPossibleMaterial.length && !bFound;j++)
                    bFound=(materials[i].getId()==iAPossibleMaterial[j]);
                if (bFound) cbType.addItem(materials[i]);
            }
        }
        cbType.addItemListener(new java.awt.event.ItemListener(){
            public void itemStateChanged(java.awt.event.ItemEvent e){
                int iIdMaterial=((ObjectListElement)cbType.getSelectedItem()).getId();
                qtiMat.setMaterialType(iIdMaterial,null);
            }
        });
        ObjectListElement ol21=new ObjectListElement(QTIMaterial.ALIGN_LEFT,Messages.getLocalizedString("Left"));
        ObjectListElement ol22=new ObjectListElement(QTIMaterial.ALIGN_CENTER,Messages.getLocalizedString("Center"));
        ObjectListElement ol23=new ObjectListElement(QTIMaterial.ALIGN_RIGHT,Messages.getLocalizedString("Right"));
        cbAlign.addItem(ol21);
        cbAlign.addItem(ol22);
        cbAlign.addItem(ol23);
    }
    
    public void setMaterialType(int iMaterialType){
        cbType.setSelectedIndex(iMaterialType);
    }
    
    protected void initMessages(){
        lbType.setText(Messages.getLocalizedString("Type"));
        lbType.setToolTipText(Messages.getLocalizedString("MaterialType"));
        cbType.setToolTipText(Messages.getLocalizedString("MaterialType"));
        lbAlign.setText(Messages.getLocalizedString("Align"));
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        if (jPanel1!=null) jPanel1.setBackground(c);
        if (spConcreteMaterialPanel!=null) spConcreteMaterialPanel.setBackground(c);
        java.awt.Color componentColor=CreatorProperties.getComponentColor();
        if (componentColor!=null){
            if (lbType!=null) lbType.setBackground(componentColor);
            if (cbType!=null) cbType.setBackground(componentColor);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAlign;
    private javax.swing.JScrollPane spConcreteMaterialPanel;
    private javax.swing.JLabel lbType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox cbType;
    private javax.swing.JComboBox cbAlign;
    // End of variables declaration//GEN-END:variables
    
}