/*
 * QTIScoringAlgorithmPanel.java
 *
 * Created on 1 de noviembre de 2002, 11:22
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIScoringAlgorithm;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;

/**
 *
 * @author  Albert
 * @version
 */
public class QTIScoringAlgorithmPanel extends javax.swing.JPanel {
    
    protected QTIScoringAlgorithm qtiScAlg;
    protected javax.swing.JPanel jpConcretePanel;
    
    /** Creates new form QTIScoringAlgorithmPanel */
    public QTIScoringAlgorithmPanel(QTIScoringAlgorithm qtiScAlg){
        this.qtiScAlg=qtiScAlg;
        initComponents();
        initComponents2();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jpNorth = new javax.swing.JPanel();
        lbAlgorithm = new javax.swing.JLabel();
        cbAlgorithm = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        lbAlgorithm.setText("Algoritme");
        jpNorth.add(lbAlgorithm);

        cbAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlgorithmActionPerformed(evt);
            }
        });

        jpNorth.add(cbAlgorithm);

        add(jpNorth, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
    
    private void initComponents2(){
        cbAlgorithm.addItem("SumofScores");
        cbAlgorithm.addItem("SumofScoresAttempted");
        cbAlgorithm.addItem("WeightedSumofScores");
        cbAlgorithm.addItem("WeightedSumofScoresAttempted");
        cbAlgorithm.addItem("ParameterWeightedSumofScores");
        cbAlgorithm.addItem("ParameterWeightedSumofScoresAttempted");
        cbAlgorithm.addItem("NumberCorrect");
        cbAlgorithm.addItem("NumberCorrectAttempted");
        cbAlgorithm.addItem("WeightedNumberCorrect");
        cbAlgorithm.addItem("WeightedNumberCorrectAttempted");
        cbAlgorithm.addItem("ParameterWeightedNumberCorrect");
        cbAlgorithm.addItem("ParameterWeightedNumberCorrectAttempted");
        cbAlgorithm.addItem("GuessingPenalty");
        cbAlgorithm.addItem("WeightedGuessingPenalty");
        cbAlgorithm.addItem("BestKfromN");
        cbAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlgorithmActionPerformed(evt);
            }
        });
    }
    
    public void setConcretePanel(javax.swing.JPanel jp){
        if (jpConcretePanel!=null){
            remove(jpConcretePanel);
        }
        jpConcretePanel=jp;
        add(jp,java.awt.BorderLayout.CENTER);
        //invalidate();
        //doLayout();
    }
    
    public void setConcreteAlgorithm(int i){
        cbAlgorithm.setSelectedIndex(i);
    }
    
  private void cbAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlgorithmActionPerformed
      int iConcreteScoringAlgorithm=cbAlgorithm.getSelectedIndex();
      qtiScAlg.setConcreteScoringAlgorithm(iConcreteScoringAlgorithm);
      // Add your handling code here:
  }//GEN-LAST:event_cbAlgorithmActionPerformed
  
  protected void initMessages(){
      lbAlgorithm.setText(Messages.getLocalizedString("Algorithm"));
      lbAlgorithm.setToolTipText(Messages.getLocalizedString("AlgorithmDesc"));
  }
  
  public void setBackground(java.awt.Color c){
      super.setBackground(c);
      if (jpNorth!=null) jpNorth.setBackground(c);
      if (lbAlgorithm!=null) lbAlgorithm.setBackground(c);
      if (cbAlgorithm!=null) cbAlgorithm.setBackground(c);
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAlgorithm;
    private javax.swing.JComboBox cbAlgorithm;
    private javax.swing.JPanel jpNorth;
    // End of variables declaration//GEN-END:variables
    
}