/*
 * QTISuperResponsesProcessingDialog.java
 *
 * Created on 7 de octubre de 2002, 18:40
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIFeedback;
import edu.xtec.qv.qti.QTISuperCondition;
import edu.xtec.qv.qti.QTISuperResponseProcessing;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;

/**
 *
 * @author  Albert
 * @version
 */
public class QTISuperResponsesProcessingDialog extends javax.swing.JDialog implements ExtendedRenderer{
    
    protected QTISuperResponseProcessing qtiSuperRespProc;
    protected QTISuperCondition qtiCond;
    //protected creator.QTIConditionResult qtiCondRes;
    protected QTIFeedback qtiFeed;
    
    /** Creates new form QTIResponsesProcessingDialog */
    public QTISuperResponsesProcessingDialog(java.awt.Frame parent, boolean modal, QTISuperResponseProcessing qtiSuperRespProc) {
        super(parent, Messages.getLocalizedString("SuperPossibleEvaluation"), modal);
        this.qtiSuperRespProc=qtiSuperRespProc;
        this.qtiCond=qtiSuperRespProc.getSuperCondition();
        this.qtiFeed=qtiSuperRespProc.getFeedback();
        //this.qtiCondRes=qtiItemRespProc.getConditionResult();
        initComponents();
        initComponents2();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
        //pack();
        setSize(460,430);
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jpCenter = new javax.swing.JPanel();
        spConditionPanel = new javax.swing.JScrollPane();
        spFeedbackPanel = new javax.swing.JScrollPane();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btOk.setText("Acceptar");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        jPanel1.add(btOk);

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jPanel1.add(btCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jpCenter.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        jpCenter.add(spConditionPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        jpCenter.add(spFeedbackPanel, gridBagConstraints);

        getContentPane().add(jpCenter, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
  private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
      // Add your handling code here:
      setVisible(false);
      dispose();
  }//GEN-LAST:event_btCancelActionPerformed
  
  private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
      // Add your handling code here:
      setVisible(false);
      qtiSuperRespProc.doOk();
      dispose();
  }//GEN-LAST:event_btOkActionPerformed
  
  private void initComponents2(){
      spConditionPanel.setBorder(new javax.swing.border.TitledBorder(Messages.getLocalizedString("Conditions")));
      spConditionPanel.setViewportView(qtiSuperRespProc.getPanel());
      spConditionPanel.setToolTipText(Messages.getLocalizedString("ConditionsDesc"));
      spFeedbackPanel.setViewportView(qtiFeed.getPanel());
      spFeedbackPanel.setToolTipText(Messages.getLocalizedString("FeedbackDesc"));
      spFeedbackPanel.setBorder(null);//
  }
  
  /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        //setVisible (false);
        //dispose ();
    }//GEN-LAST:event_closeDialog
    
    protected void initMessages(){
        btOk.setText(Messages.getLocalizedString("Accept"));
        btCancel.setText(Messages.getLocalizedString("Cancel"));
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        if (spFeedbackPanel!=null) spFeedbackPanel.setBackground(c);
        if (spConditionPanel!=null) spConditionPanel.setBackground(c);
        if (jpCenter!=null) jpCenter.setBackground(c);
        if (jPanel1!=null) jPanel1.setBackground(c);
        java.awt.Color componentColor=CreatorProperties.getComponentColor();
        if (componentColor!=null){
            if (btCancel!=null) btCancel.setBackground(componentColor);
            if (btOk!=null) btOk.setBackground(componentColor);
        }
    }
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spFeedbackPanel;
    private javax.swing.JScrollPane spConditionPanel;
    private javax.swing.JButton btCancel;
    private javax.swing.JPanel jpCenter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton btOk;
    // End of variables declaration//GEN-END:variables
    
}