/*
 * QTISelectionResponseDialog.java
 *
 * Created on 21 / maig / 2003, 12:57
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.util.Messages;

/**
 *
 * @author  allastar
 */
public class QTISelectionResponseDialog extends javax.swing.JDialog {
    
    boolean bOk=false;
    QTISelectionResponsePanel p;
    
    /** Creates new form QTISelectionResponseDialog */
    public QTISelectionResponseDialog(java.awt.Frame parent, QTISelectionResponsePanel p, boolean modal) {
        super(/*manage.ManageFrame.frame*/parent, Messages.getLocalizedString("AddOptionDesc"), modal);
        this.p=p;
        initComponents();
        initComponents2();
        initMessages();
        setSize(345,300);
    }
    
    public boolean isOk(){
        return bOk;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        btAccept = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btAccept.setText("Acceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        jPanel1.add(btAccept);

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jPanel1.add(btCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    protected void initComponents2(){
        getContentPane().add(p,java.awt.BorderLayout.CENTER);
        pack();
    }
    
    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // Add your handling code here:
        bOk=false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // Add your handling code here:
        bOk=true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btAcceptActionPerformed
    
    protected void initMessages(){
        btAccept.setText(Messages.getLocalizedString("Accept"));
        btCancel.setText(Messages.getLocalizedString("Cancel"));
    }    

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public void show(){
        ////p.requestIdentFieldFocus();
        super.show();
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        new QTISelectionResponseDialog(new javax.swing.JFrame(), true).show();
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JButton btCancel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
