/*
 * QTISuperConditionDialog.java
 *
 * Created on 19 / maig / 2003, 15:56
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.util.Messages;

/**
 *
 * @author  allastar
 */
public class QTISuperConditionDialog extends javax.swing.JDialog{
    
    QTISuperConditionPanel p;
    boolean bOk=false;
    
    /** Creates new form QTISuperConditionDialog */
    public QTISuperConditionDialog(java.awt.Frame parent, QTISuperConditionPanel p, boolean modal) {
        super(parent, Messages.getLocalizedString("SuperResponseCondition"), modal);
        this.p=p;
        //final QTISuperConditionPanel p2=p;
        p.addOperandKeyListener(new java.awt.event.KeyAdapter(){
            public void keyReleased(java.awt.event.KeyEvent e){
                checkButtons();
            }
        });
        initComponents();
        initComponents2();
        checkButtons();
        initMessages();
        pack();
        //setSize(width
    }
    
    protected void checkButtons(){
        if (p.getOperand()!=null && p.getOperand().length()>0) btAccept.setEnabled(true);
        else btAccept.setEnabled(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        btAccept = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btAccept.setText("jButton1");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        jPanel1.add(btAccept);

        btCancel.setText("jButton2");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jPanel1.add(btCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // Add your handling code here:
        bOk=false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // Add your handling code here:
        bOk=true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btAcceptActionPerformed
    
    protected void initComponents2(){
        //getContentPane().setLayout(new java.awt.BorderLayout());
        if (p!=null) getContentPane().add(p,java.awt.BorderLayout.CENTER);
    }
    
    protected void initMessages(){
        btAccept.setText(Messages.getLocalizedString("Accept"));
        btCancel.setText(Messages.getLocalizedString("Cancel"));
    }

    public boolean isOk(){
        return bOk;
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        new QTISuperConditionDialog(new javax.swing.JFrame(), true).show();
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JButton btCancel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
