/*
 * QTITextMaterialPanel.java
 *
 * Created on 6 de octubre de 2002, 20:06
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTITextMaterial;
import edu.xtec.qv.qti.util.CreatorProperties;

/**
 *
 * @author  Albert
 * @version
 */
public class QTITextMaterialPanel extends javax.swing.JPanel implements ExtendedRenderer{
    
    protected QTITextMaterial qtiTextMat;
    
    /** Creates new form QTITextMaterialPanel */
    public QTITextMaterialPanel(QTITextMaterial qtiTextMat, String sText){
        this.qtiTextMat=qtiTextMat;
        initComponents();
        initComponents2();
        jtaText.setText(sText);
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
    }
    
    public String getText(){
        return jtaText.getText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jtaText = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        add(jtaText, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    protected void initComponents2(){
    }
    
    public void setBackground(java.awt.Color c){
        super.setBackground(c);
        //if (spText!=null) spText.setBackground(c);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jtaText;
    // End of variables declaration//GEN-END:variables
    
}