/*
 * QTIWeightedGuessingScoringAlgorithmPanel.java
 *
 * Created on 4 / novembre / 2002, 09:21
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;

/**
 *
 * @author  allastar
 */
public class QTIWeightedGuessingScoringAlgorithmPanel extends javax.swing.JPanel {
    
    /** Creates new form QTIWeightedGuessingScoringAlgorithmPanel */
    public QTIWeightedGuessingScoringAlgorithmPanel() {
        initComponents();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    public void setWeight(String sWeight){
        tfWeight.setText(sWeight);
    }
	
    public String getWeight(){
	return tfWeight.getText();
    }

    public void setPenalty(String sPenalty){
	tfPenalty.setText(sPenalty);
    }
	
    public String getPenalty(){
	return tfPenalty.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lbWeight = new javax.swing.JLabel();
        tfWeight = new javax.swing.JTextField();
        lbPenalty = new javax.swing.JLabel();
        tfPenalty = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        lbWeight.setText("Pes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(lbWeight, gridBagConstraints);

        tfWeight.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(tfWeight, gridBagConstraints);

        lbPenalty.setText("Penalitzaci\u00f3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(lbPenalty, gridBagConstraints);

        tfPenalty.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(tfPenalty, gridBagConstraints);

    }//GEN-END:initComponents
    
    protected void initMessages(){
			lbWeight.setText(Messages.getLocalizedString("Weight"));
			lbPenalty.setText(Messages.getLocalizedString("Penalty"));
		}

    public void setBackground(java.awt.Color c){
   		super.setBackground(c);
   		if (lbWeight!=null) lbWeight.setBackground(c);
   		if (tfWeight!=null) tfWeight.setBackground(c);
   		if (lbPenalty!=null) lbPenalty.setBackground(c);
   		if (tfPenalty!=null) tfPenalty.setBackground(c);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbPenalty;
    private javax.swing.JTextField tfWeight;
    private javax.swing.JTextField tfPenalty;
    private javax.swing.JLabel lbWeight;
    // End of variables declaration//GEN-END:variables
    
}