/*
 * SaveAssessmentDialog.java
 *
 * Created on 6 / novembre / 2002, 08:56
 */

package edu.xtec.qv.editor.ui;

import edu.xtec.qv.qti.QTIAssessment;
import edu.xtec.qv.qti.util.CreatorProperties;
import edu.xtec.util.Messages;
/**
 *
 * @author  allastar
 */
public class SaveAssessmentDialog extends javax.swing.JDialog {
    
    protected QTIAssessment qtiAssessment;
    
    /** Creates new form SaveAssessmentDialog */
    public SaveAssessmentDialog(QTIAssessment qtiAssessment, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.qtiAssessment=qtiAssessment;
        initComponents();
        if (CreatorProperties.getBackground()!=null || CreatorProperties.getComponentColor()!=null) setBackground(CreatorProperties.getBackground());
        initMessages();
    }
    
    public void selectFileOption(){
        rbFile.setSelected(true);
    }
    
    public void selectDBOption(){
        rbDB.setSelected(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbSaveLocation = new javax.swing.JLabel();
        jpButtons = new javax.swing.JPanel();
        btAccept = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jpLocation = new javax.swing.JPanel();
        rbFile = new javax.swing.JRadioButton();
        rbDB = new javax.swing.JRadioButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        lbSaveLocation.setText("On ho vols desar?");
        lbSaveLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSaveLocation.setFont(new java.awt.Font("Dialog", 1, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 2, 15, 2);
        getContentPane().add(lbSaveLocation, gridBagConstraints);

        btAccept.setText("Acceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        jpButtons.add(btAccept);

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jpButtons.add(btCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 8, 8);
        getContentPane().add(jpButtons, gridBagConstraints);

        jpLocation.setLayout(new java.awt.GridLayout(2, 0));

        rbFile.setText("Fitxer");
        buttonGroup1.add(rbFile);
        jpLocation.add(rbFile);

        rbDB.setText("Base de Dades");
        buttonGroup1.add(rbDB);
        jpLocation.add(rbDB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(jpLocation, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
        if (rbFile.isSelected()) qtiAssessment.doSaveIn(QTIAssessment.FILE);
        else qtiAssessment.doSaveIn(QTIAssessment.DB);
    }//GEN-LAST:event_btAcceptActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    protected void initMessages(){
			lbSaveLocation.setText(Messages.getLocalizedString("SaveLocation"));
			btAccept.setText(Messages.getLocalizedString("Accept"));
			btCancel.setText(Messages.getLocalizedString("Cancel"));
			rbFile.setText(Messages.getLocalizedString("File"));
			rbDB.setText(Messages.getLocalizedString("Database"));
		}
    
    public void setBackground(java.awt.Color c){
			super.setBackground(c);
    	if (rbFile!=null) rbFile.setBackground(c);
    	if (btAccept!=null) btAccept.setBackground(c);
    	if (rbDB!=null) rbDB.setBackground(c);
    	if (btCancel!=null) btCancel.setBackground(c);
    	if (jpLocation!=null) jpLocation.setBackground(c);
    	if (lbSaveLocation!=null) lbSaveLocation.setBackground(c);
    	if (jpButtons!=null) jpButtons.setBackground(c);
		}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton rbFile;
    private javax.swing.JButton btAccept;
    private javax.swing.JRadioButton rbDB;
    private javax.swing.JButton btCancel;
    private javax.swing.JPanel jpLocation;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbSaveLocation;
    private javax.swing.JPanel jpButtons;
    // End of variables declaration//GEN-END:variables
    
}