/*
 * HolesEditorFrame.java
 *
 * Created on 10 / juny / 2003, 12:37
 */

package edu.xtec.qv.editor.shapers;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;

import edu.xtec.jclic.boxes.BoxBase;
import edu.xtec.jclic.shapers.Holes;
import edu.xtec.jclic.shapers.HolesEditorPanel;
import edu.xtec.jclic.shapers.utils.ShapeInfo;
import edu.xtec.qv.editor.ManageFrame;
import edu.xtec.qv.qti.QTIHotspot;
import edu.xtec.util.Messages;
import edu.xtec.util.Options;

/**
 *
 * @author  allastar
 */
public class HolesEditorFrame extends javax.swing.JDialog {//extends javax.swing.JFrame {
    
    public HolesEditorPanel hep;
    QTIHotspot qtiHot;
    
    /** Creates new form HolesEditorFrame */
    public HolesEditorFrame(QTIHotspot qtiHot, Holes h, Image i) {
        super(ManageFrame.frame,Messages.getLocalizedString("ShapesEditor"),true);
        this.qtiHot=qtiHot;
        initComponents();
        Options options=new Options();//null;
        hep=new HolesEditorPanel(options, h, new Dimension(400,300), i, new BoxBase());
        initComponents2();
        setSize(750,500);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        btAccept = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        btAccept.setText("Acceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        jPanel1.add(btAccept);

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jPanel1.add(btCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // Add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // Add your handling code here:
        hep.confirmChanges();
        java.util.Vector v=new java.util.Vector();
        //System.out.println("w="+hep.previewArea.width+" h="+hep.previewArea.height);
        for (int i=0;i<hep.getHoles().getNumCells();i++){
            edu.xtec.jclic.shapers.ShapeData sd=hep.getHoles().getShapeData(i); //.getShape(i,hep.previewArea);
            sd.scaleTo(1.0/(hep.previewArea.width/hep.xFactor),1.0/(hep.previewArea.height/hep.yFactor)); //Perquè torni a les mides reals
            ShapeInfo si=new ShapeInfo(sd.comment,sd);
            //System.out.println("final 1 "+si.getType()+" "+si.getArea());
            v.add(si);
        }
        qtiHot.setShapes(v);
        setVisible(false);
    }//GEN-LAST:event_btAcceptActionPerformed
    
    protected void initComponents2(){
        getContentPane().add(hep,BorderLayout.CENTER);
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        ////System.exit(0);
        setVisible(false);
        ////dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        new HolesEditorFrame().show();
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JButton btCancel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
